package sdk

import (
	"context"
	"strings"

	apierrors "k8s.io/apimachinery/pkg/api/errors"

	"console/internal/consts"
	"console/internal/errs"
	k8s "console/internal/kubernetes"
	"console/internal/model"
)

// DomainService 对应 Java 的 DomainServiceImpl
type DomainService struct {
	client       *k8s.Client
	converter    *Converter
	routeService *RouteService
	wasmInstance *WasmPluginInstanceService
}

// NewDomainService 创建 DomainService
func NewDomainService(client *k8s.Client, converter *Converter, routeService *RouteService,
	wasmInstance *WasmPluginInstanceService) *DomainService {
	return &DomainService{client: client, converter: converter, routeService: routeService, wasmInstance: wasmInstance}
}

// Add 对应 add
func (s *DomainService) Add(domain *model.Domain) *model.Domain {
	cm := s.converter.Domain2ConfigMap(domain)
	newCm, err := s.client.CreateConfigMap(context.Background(), cm)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when adding a new domain."))
	}
	s.syncRouteDomainConfigs(deref(domain.Name))
	return s.converter.ConfigMap2Domain(newCm)
}

// List 对应 list
func (s *DomainService) List(query *model.CommonPageQuery) *model.PaginatedResult[model.Domain] {
	cms, err := s.client.ListConfigMap(context.Background(), nil)
	if err != nil {
		panic(errs.Business("Error occurs when listing ConfigMap."))
	}
	var domains []model.Domain
	for i := range cms {
		if strings.HasPrefix(cms[i].Name, consts.DomainPrefix) {
			domains = append(domains, *s.converter.ConfigMap2Domain(&cms[i]))
		}
	}
	return model.CreateFromFullList(domains, query)
}

// Query 对应 query
func (s *DomainService) Query(domainName string) *model.Domain {
	name := s.converter.DomainName2ConfigMapName(domainName)
	cm, err := s.client.ReadConfigMap(context.Background(), name)
	if err != nil {
		panic(errs.Business("Error occurs when reading the ConfigMap with name: " + name))
	}
	if cm == nil {
		return nil
	}
	return s.converter.ConfigMap2Domain(cm)
}

// Delete 对应 delete
func (s *DomainService) Delete(domainName string) {
	query := &model.RoutePageQuery{DomainName: strPtr(domainName)}
	routes := s.routeService.List(query)
	if len(routes.Data) > 0 {
		panic(errs.Internal("The domain has routes. Please delete them first."))
	}
	name := s.converter.DomainName2ConfigMapName(domainName)
	if err := s.client.DeleteConfigMap(context.Background(), name); err != nil {
		panic(errs.Business("Error occurs when deleting the ConfigMap with name: " + name))
	}
	s.wasmInstance.DeleteAll(model.ScopeDomain, domainName)
}

// Put 对应 put
func (s *DomainService) Put(domain *model.Domain) *model.Domain {
	cm := s.converter.Domain2ConfigMap(domain)
	updated, err := s.client.ReplaceConfigMap(context.Background(), cm)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when replacing the ConfigMap generated by domain: " + deref(domain.Name)))
	}
	s.syncRouteDomainConfigs(deref(domain.Name))
	return s.converter.ConfigMap2Domain(updated)
}

func (s *DomainService) syncRouteDomainConfigs(domainName string) {
	var routes []model.Route
	if consts.DefaultDomain == domainName {
		result := s.routeService.List(nil)
		for _, r := range result.Data {
			if len(r.Domains) == 0 {
				routes = append(routes, r)
			}
		}
	} else {
		query := &model.RoutePageQuery{DomainName: strPtr(domainName)}
		routes = s.routeService.List(query).Data
	}
	for i := range routes {
		r := routes[i]
		s.routeService.Update(&r)
	}
}
