package sdk

import (
	"context"

	networkingv1 "k8s.io/api/networking/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"

	"console/internal/errs"
	k8s "console/internal/kubernetes"
	"console/internal/model"
)

// RouteService 对应 Java 的 RouteServiceImpl
type RouteService struct {
	client       *k8s.Client
	converter    *Converter
	wasmInstance *WasmPluginInstanceService
	consumer     *ConsumerService
}

// NewRouteService 创建 RouteService
func NewRouteService(client *k8s.Client, converter *Converter, wasmInstance *WasmPluginInstanceService,
	consumer *ConsumerService) *RouteService {
	return &RouteService{client: client, converter: converter, wasmInstance: wasmInstance, consumer: consumer}
}

// List 对应 list
func (s *RouteService) List(query *model.RoutePageQuery) *model.PaginatedResult[model.Route] {
	if query == nil {
		query = &model.RoutePageQuery{}
	}
	ingresses := s.listIngresses(query)
	if len(ingresses) == 0 {
		return model.CreateFromFullList([]model.Route{}, &query.CommonPageQuery)
	}
	allowLists := s.consumer.ListAllowLists()
	var routes []model.Route
	for i := range ingresses {
		routeName := ingresses[i].Name
		var allowList *model.AllowList
		for j := range allowLists {
			a := &allowLists[j]
			if len(a.Targets) == 1 && a.Targets[model.ScopeRoute] != nil && *a.Targets[model.ScopeRoute] == routeName {
				allowList = a
				break
			}
		}
		routes = append(routes, *s.ingress2Route(&ingresses[i], allowList))
	}
	return model.CreateFromFullList(routes, &query.CommonPageQuery)
}

func (s *RouteService) listIngresses(query *model.RoutePageQuery) []networkingv1.Ingress {
	if query == nil {
		query = &model.RoutePageQuery{}
	}
	var ingresses []networkingv1.Ingress
	var err error
	if query.DomainName != nil && *query.DomainName != "" {
		if query.All != nil && *query.All {
			panic(errs.Validation("The query parameter 'all' is not supported when querying by domain."))
		}
		ingresses, err = s.client.ListIngressByDomain(context.Background(), *query.DomainName)
	} else if query.All != nil && *query.All {
		ingresses, err = s.client.ListAllIngresses(context.Background())
	} else {
		ingresses, err = s.client.ListIngress(context.Background(), nil)
	}
	if err != nil {
		panic(errs.Business("Error occurs when listing Ingresses."))
	}
	return ingresses
}

// Query 对应 query
func (s *RouteService) Query(routeName string) *model.Route {
	ingress, err := s.client.ReadIngress(context.Background(), routeName)
	if err != nil {
		panic(errs.Business("Error occurs when reading the Ingress with name: " + routeName))
	}
	if ingress == nil {
		return nil
	}
	allowList := s.consumer.GetAllowList(map[model.WasmPluginInstanceScope]*string{model.ScopeRoute: strPtr(routeName)})
	return s.ingress2Route(ingress, allowList)
}

// Add 对应 add
func (s *RouteService) Add(route *model.Route) *model.Route {
	ingress := s.converter.Route2Ingress(route)
	newIngress, err := s.client.CreateIngress(context.Background(), ingress)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when adding the ingress generated by route with name: " + deref(route.Name)))
	}
	s.writeAuthConfigResources(deref(route.Name), route.AuthConfig)
	return s.converter.Ingress2Route(newIngress)
}

// Update 对应 update
func (s *RouteService) Update(route *model.Route) *model.Route {
	ingress := s.converter.Route2Ingress(route)
	updated, err := s.client.ReplaceIngress(context.Background(), ingress)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when updating the ingress generated by route with name: " + deref(route.Name)))
	}
	s.writeAuthConfigResources(deref(route.Name), route.AuthConfig)
	return s.converter.Ingress2Route(updated)
}

// Delete 对应 delete
func (s *RouteService) Delete(name string) {
	if err := s.client.DeleteIngress(context.Background(), name); err != nil {
		panic(errs.Business("Error occurs when deleting ingress with name: " + name))
	}
	s.wasmInstance.DeleteAll(model.ScopeRoute, name)
}

func (s *RouteService) writeAuthConfigResources(routeName string, authConfig *model.RouteAuthConfig) {
	if authConfig == nil {
		authConfig = &model.RouteAuthConfig{Enabled: boolPtr(false)}
	}
	allowList := &model.AllowList{
		Targets:         map[model.WasmPluginInstanceScope]*string{model.ScopeRoute: strPtr(routeName)},
		AuthEnabled:     authConfig.Enabled,
		CredentialTypes: authConfig.AllowedCredentialTypes,
		ConsumerNames:   authConfig.AllowedConsumers,
	}
	s.consumer.UpdateAllowList(model.AllowListReplace, allowList)
}

func (s *RouteService) ingress2Route(ingress *networkingv1.Ingress, allowList *model.AllowList) *model.Route {
	route := s.converter.Ingress2Route(ingress)
	authConfig := &model.RouteAuthConfig{}
	if allowList == nil {
		authConfig.Enabled = boolPtr(false)
	} else {
		authConfig.Enabled = allowList.AuthEnabled
		authConfig.AllowedCredentialTypes = allowList.CredentialTypes
		authConfig.AllowedConsumers = allowList.ConsumerNames
	}
	route.AuthConfig = authConfig
	return route
}
