package sdk

import (
	"context"

	apierrors "k8s.io/apimachinery/pkg/api/errors"

	"console/internal/consts"
	"console/internal/errs"
	k8s "console/internal/kubernetes"
	"console/internal/model"
)

// TlsCertificateService 对应 Java 的 TlsCertificateServiceImpl
type TlsCertificateService struct {
	client    *k8s.Client
	converter *Converter
}

// NewTlsCertificateService 创建 TlsCertificateService
func NewTlsCertificateService(client *k8s.Client, converter *Converter) *TlsCertificateService {
	return &TlsCertificateService{client: client, converter: converter}
}

// List 对应 list
func (s *TlsCertificateService) List(query *model.CommonPageQuery) *model.PaginatedResult[model.TlsCertificate] {
	secrets, err := s.client.ListSecret(context.Background(), consts.SecretTypeTLS)
	if err != nil {
		panic(errs.Business("Error occurs when listing Secret."))
	}
	var certs []model.TlsCertificate
	for i := range secrets {
		certs = append(certs, *s.converter.Secret2TlsCertificate(&secrets[i]))
	}
	return model.CreateFromFullList(certs, query)
}

// Query 对应 query
func (s *TlsCertificateService) Query(name string) *model.TlsCertificate {
	secret, err := s.client.ReadSecret(context.Background(), name)
	if err != nil {
		panic(errs.Business("Error occurs when reading the Secret with name: " + name))
	}
	if secret == nil {
		return nil
	}
	if string(secret.Type) != consts.SecretTypeTLS {
		return nil
	}
	return s.converter.Secret2TlsCertificate(secret)
}

// Add 对应 add
func (s *TlsCertificateService) Add(certificate *model.TlsCertificate) *model.TlsCertificate {
	secret := s.converter.TlsCertificate2Secret(certificate)
	newSecret, err := s.client.CreateSecret(context.Background(), secret)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when adding the secret generated by tls certificate with name: " +
			deref(certificate.Name)))
	}
	return s.converter.Secret2TlsCertificate(newSecret)
}

// Update 对应 update
func (s *TlsCertificateService) Update(certificate *model.TlsCertificate) *model.TlsCertificate {
	secret := s.converter.TlsCertificate2Secret(certificate)
	newSecret, err := s.client.ReplaceSecret(context.Background(), secret)
	if err != nil {
		if apierrors.IsConflict(err) {
			panic(errs.Conflict(""))
		}
		panic(errs.Business("Error occurs when updating the secret generated by tls certificate with name: " +
			deref(certificate.Name)))
	}
	return s.converter.Secret2TlsCertificate(newSecret)
}

// Delete 对应 delete
func (s *TlsCertificateService) Delete(name string) {
	if err := s.client.DeleteSecret(context.Background(), name); err != nil {
		panic(errs.Business("Error occurs when deleting secret with name: " + name))
	}
}
